File/Folder Renaming
madhmanoj/ide_testbed pull request #3
Opened 2024-11-09 12:28 UTC by madhmanoj

- Added File/Folder renaming using contextmenu
- Integrated File/Folder renaming on creation

2024-11-14 09:03 UTC, allsey87 requested changes
This is a good attempt, however, the putting the rename field inside of `File` and `Directory` is not correct. As mentioned in my comment, renaming a file is related to the state of the UI not the state of the file/directory.

There are also some styling issues with the input box sitting on the line under the icon and overflowing the panel. Using the correct CSS classes for Bulma should fix this. I would start with [Bulma/Forms](https://versions.bulma.io/0.9.3/documentation/form/general/), although you may need to nest your HTML input element within other elements/classes for it to render correctly

![image](https://github.com/user-attachments/assets/818630df-f4d9-4c6d-92df-c1890572f6f4)

It is also possible to rename multiple files/folders at the same time which in itself is not strictly a problem, but if you click somewhere else in the UI it should end the rename operation.

![image](https://github.com/user-attachments/assets/cc1dd100-e972-4376-aa5e-8e8aca2891ad)

2024-11-14 09:03 UTC, allsey87 commented on crates/frontend/src/vfs/mod.rs
> +    pub rename: Mutable<bool>
While this does work, it does not make a lot of sense. The problem here is that whether or not a file is being currently renamed is the state of the GUI, not the state of a file.

2024-12-12 11:09 UTC, madhmanoj commented
> This is a good attempt, however, the putting the rename field inside of `File` and `Directory` is not correct. As mentioned in my comment, renaming a file is related to the state of the UI not the state of the file/directory.
> 
> There are also some styling issues with the input box sitting on the line under the icon and overflowing the panel. Using the correct CSS classes for Bulma should fix this. I would start with [Bulma/Forms](https://versions.bulma.io/0.9.3/documentation/form/general/), although you may need to nest your HTML input element within other elements/classes for it to render correctly
> 
> ![image](https://private-user-images.githubusercontent.com/3796345/386115281-818630df-f4d9-4c6d-92df-c1890572f6f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMDE2NTIsIm5iZiI6MTczNDAwMTM1MiwicGF0aCI6Ii8zNzk2MzQ1LzM4NjExNTI4MS04MTg2MzBkZi1mNGQ5LTRjNmQtOTJkZi1jMTg5MDU3MmY2ZjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTJUMTEwMjMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmZmZjhkOTYzOTExYjYxMDIyZjM5NGI0MjY0ZTA5NjUxNzA3YzdmZjU0MTA4MmJlMDhmNzA4ZmIwY2M0M2IxNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.td91Xm95g79NDgcs15nB0EAtny5PYEzEmDupmSKsdvU)
> 
> It is also possible to rename multiple files/folders at the same time which in itself is not strictly a problem, but if you click somewhere else in the UI it should end the rename operation.
> 
> ![image](https://private-user-images.githubusercontent.com/3796345/386117137-cc1dd100-e972-4376-aa5e-8e8aca2891ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMDE2NTIsIm5iZiI6MTczNDAwMTM1MiwicGF0aCI6Ii8zNzk2MzQ1LzM4NjExNzEzNy1jYzFkZDEwMC1lOTcyLTQzNzYtYWE1ZS04ZThhY2EyODkxYWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTJUMTEwMjMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTZmMTVkNWZkZGU0N2Q1NjY2N2YzZGYyMzI0OTRjOGQwOWExMTViN2QzNmQ2N2U1ZGIzZTk1YWI5M2NkYTA0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.VrK88ZJ-mqDLb2yNavTlFDu_eNpS5zY0BFBn31iTe_w)

Can `rename` variable be a part of the `Explorer`, the renaming will then be related to the state of the UI and we can also take care of the multiple renaming since the renaming is controlled by a common variable.

2024-12-17 14:08 UTC, allsey87 approved these changes
LGTM!

2024-12-17 14:12 UTC, allsey87 commented
Sorry, somehow I didn't get notified about the previous comment. If I haven't responded after a day feel free to send me a message on Whatsapp.

> Can rename variable be a part of the Explorer, the renaming will then be related to the state of the UI and we can also take care of the multiple renaming since the renaming is controlled by a common variable.

I think you have taken a different approach now, but I would say that having a rename variable in the Explorer widget makes sense since performing a rename operation is part of the state of a widget. I see that you have used `thread_local!` statics for this now but since we are almost at the end of the project, I would not worry about changing it.

2025-01-22 14:45 UTC, allsey87 requested changes

2025-01-22 14:45 UTC, allsey87 commented on crates/frontend/src/sidebar/mod.rs
> +                    .apply(|dom| vertical_resizer(dom, &RESIZER_PX, &this.resize_active, &this.resizer_hover))
Move `RESIZER_PX` to styles.rs

2025-01-22 14:45 UTC, allsey87 commented on crates/frontend/src/styles.rs
> +// MAIN CONTAINER
Add constants for widths and heights, colors, and other?

2025-01-22 14:45 UTC, allsey87 commented on crates/frontend/src/styles.rs
> +}
Add mod.rs, and move this code to a tabs.rs

2025-01-22 14:45 UTC, allsey87 commented on crates/frontend/src/styles.rs
> +}
When using the style, always include the full path, e.g.,
```
use crate::styles;
// use full path to style function
.apply(styles::tabs::icon)

```

2025-01-23 21:12 UTC, allsey87 reviewed
Looking good, but there are still a few things that I found that could be improved.

One thing to keep in mind is that the functions in the style module should be composable and reusable. The idea isn't to bring every single call to `DomBuilder::class` and `DomBuilder::style` into this module. Rather, we should only include groups of styles that apply to multiple elements in our layout. The point is that if we want to change the color, thickness, padding of all instances of component X in our layout, we can do that from exactly one place. For example:
```rust
// styles.rs
fn my_substyle<T>(builder: DomBuilder<T>) -> DomBuilder<T> {
   builder
      .class("class1")
      .class("class2")
}

fn my_style1<T>(builder: DomBuilder<T>) -> DomBuilder<T> {
   builder
      .apply(my_substyle) // styles that apply both to my_style1 and my_style2
      .class("class3")
}

fn my_style2<T>(builder: DomBuilder<T>) -> DomBuilder<T> {
   builder
      .apply(my_substyle) // styles that apply both to my_style1 and my_style2
      .class("class4")
}

// component.rs
html!("div", {
   .apply(my_style2)
   .class("class5") // this is fine if this class only applies to this specific instance
})
```

Moreover, I also suspect that logic around the grid layout and the sizing of components (height, width) belongs in component.rs. I am not 100% sure about this yet. Think about it and try to come up with some convincing arguments for/against doing this.

Another thing to pay attention to is that the structuring of the divs is very much a result of the Bulma classes that were originally used, e.g., a `<div class="column">` had to be placed inside a `<div class="columns">`. So it may be possible to strip out a couple layer of divs here and there which will clean up the code/simplify the layout. Please do this whenever possible.

2025-01-23 21:12 UTC, allsey87 commented on crates/frontend/src/styles/console.rs
> +        .style("height", "calc(100% - 40px)") // 40 px for the block above
We should get rid of things like `calc(100% - 40px)`. I put these hacks in place since Bulma was a bit limited in what it could do. We should be able to use Tailwind and Grid CSS to achieve the desired effect.

2025-01-23 21:12 UTC, allsey87 commented on crates/frontend/src/styles/console.rs
> +        .class("text-[#090a0c]")
Perhaps factor these color classes out into constants, such as `TEXT_COLOR`, `BACKGROUND_COLOR` etc?

2025-01-23 21:12 UTC, allsey87 commented on crates/frontend/src/styles/menu.rs
> +}
I would keep just one of these functions and give it a generic name. Keep in mind the idea is not to have one style function per element, but rather to organise the styles logically

2025-01-23 21:12 UTC, allsey87 commented on styles.css
> +    }
These should be migrated into the styles module, right?

2025-01-23 21:12 UTC, allsey87 commented on tailwind.config.js
> +        'gray': '#e9e9e9'
Perhaps our theme can also be migrated into the styles module? This way all the look and feel logic is in one place.

2025-01-23 21:12 UTC, allsey87 commented on crates/frontend/src/styles/menu.rs
> +pub fn button_explorer(dom: DomBuilder<SvgElement>, active: &Broadcaster<impl Signal<Item = bool> + 'static>) -> DomBuilder<SvgElement> {
It's more idiomatic to just pass in a `impl Signal<Item = bool>` and to create the broadcaster inside of this function.

2025-01-24 20:10 UTC, allsey87 commented on crates/frontend/src/styles/menu.rs
> +pub fn button_explorer(dom: DomBuilder<SvgElement>, active: &Broadcaster<impl Signal<Item = bool> + 'static>) -> DomBuilder<SvgElement> {
This is actually super important since instead of:
```rust
use crate::workspace::activity_panel::Activity;

// There should be a better way to handle the last class_signal and its related variables
pub fn body(dom: DomBuilder<HtmlElement>,
    is_active: MutableSignalRef<Option<Rc<Activity>>, impl FnMut(&Option<Rc<Activity>>) -> bool + 'static>,
    mouse_over: &Mutable<bool>
) -> DomBuilder<HtmlElement> {
    dom.class("block")
        .class("h-full")
        .class("gap-1")
        .class("pt-1.5")
        .class("cursor-pointer")
        .class_signal("bg-white",signal::or(
            is_active,
            mouse_over.signal())
        )
}
```
You can just write:
```rust
pub fn body(
    dom: DomBuilder<HtmlElement>,
    is_active: impl Signal<Item = bool> + 'static,
    mouse_over: impl Signal<Item = bool> + 'static,
) -> DomBuilder<HtmlElement> {
    dom.class("block")
        .class("h-full")
        .class("gap-1")
        .class("pt-1.5")
        .class("cursor-pointer")
        .class_signal("bg-white",signal::or(
            is_active,
            mouse_over.signal())
        )
}
```
Note how styles no longer has a dependency on `crate::workspace::activity_panel::Activity`, these sorts of dependency loops can get really ugly, really quickly. Avoid them for your own sanity ;)

2025-01-25 14:53 UTC, merged